spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog-db
    username: postgres
    password: P@ssword1
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jdbc:
    template:
      query-timeout: 30s
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 100
  threads:
    virtual:
      enabled: true
  mvc:
    apiversion:
      supported: "1.0"
      default-version: "1.0"
      use:
        header: "Cartify-API-Version"
  modulith:
    runtime:
      verification-enabled: true
    events:
      jdbc:
        schema-initialization:
          enabled: true
        use-legacy-structure: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true