spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:2}
  jdbc:
    template:
      query-timeout: 30s
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 100
  threads:
    virtual:
      enabled: true
  modulith:
    runtime:
      verification-enabled: true
    events:
      jdbc:
        schema-initialization:
          enabled: true
        use-legacy-structure: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true