### Get Category by ID (admin)
GET http://localhost:8080/api/categories/admin/1
Accept: application/json

###

### Get Category by ID - Fashion
GET http://localhost:8080/api/categories/admin/2
Accept: application/json

###

### Get Category by ID - Not Found
GET http://localhost:8080/api/categories/admin/9999
Accept: application/json
