### Get Subcategories (admin) - Electronics
GET http://localhost:8080/api/categories/admin/1/subcategories
Accept: application/json

###

### Get Subcategories (admin) - Fashion
GET http://localhost:8080/api/categories/admin/2/subcategories
Accept: application/json

###

### Get Subcategories (admin) - Category with no children
GET http://localhost:8080/api/categories/admin/11/subcategories
Accept: application/json

###

### Get Subcategories (admin) - Not Found
GET http://localhost:8080/api/categories/admin/9999/subcategories
Accept: application/json
