### Get Subcategories by Parent ID (public view)
GET http://localhost:8080/api/categories?parentId=1
Accept: application/json

###

### Get Subcategories - Electronics (id=1), page 2
GET http://localhost:8080/api/categories?parentId=1&page=2&size=3
Accept: application/json

###

### Get Subcategories - Fashion (id=2)
GET http://localhost:8080/api/categories?parentId=2
Accept: application/json
