### Get All Categories (default page)
GET http://localhost:8080/api/categories
Accept: application/json

###

### Get All Categories - Page 2
GET http://localhost:8080/api/categories?page=2&size=10
Accept: application/json

###

### Get All Categories - Custom sort
GET http://localhost:8080/api/categories?page=1&size=5&sort=displayOrder,asc
Accept: application/json
