CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       BIGINT DEFAULT 0                        NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    slug          VARCHAR(150)                            NOT NULL,
    image_url     VARCHAR(200),
    status        VARCHAR(255)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    parent_id     BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uq_category_slug UNIQUE (slug);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

CREATE INDEX idx_category_display_order ON categories (display_order);

CREATE INDEX idx_category_name ON categories (name);

CREATE INDEX idx_category_status ON categories (status);

CREATE INDEX idx_category_parent_id ON categories (parent_id);