CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    slug          VARCHAR(150)                            NOT NULL,
    image_url     VARCHAR(255),
    status        VARCHAR(255)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    parent_id     BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uk_category_slug UNIQUE (slug);

CREATE INDEX category_name_idx ON categories (name);

CREATE INDEX category_status_idx ON categories (status);

CREATE INDEX category_display_order_idx ON categories (display_order, id);

CREATE INDEX category_parent_status_idx ON categories (parent_id, status);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);