CREATE TABLE categories_meta
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     TEXT,
    seo_title       VARCHAR(70),
    seo_description VARCHAR(320),
    category_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_categories_meta PRIMARY KEY (id)
);

ALTER TABLE categories_meta
    ADD CONSTRAINT uk_category_meta_category_id UNIQUE (category_id);

ALTER TABLE categories_meta
    ADD CONSTRAINT FK_CATEGORIES_META_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE;