CREATE TABLE option_types
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    product_id    UUID                                    NOT NULL,
    CONSTRAINT pk_option_types PRIMARY KEY (id)
);

ALTER TABLE option_types
    ADD CONSTRAINT FK_OPTION_TYPES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX option_type_product_idx ON option_types (product_id);