CREATE TABLE option_values
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value          VARCHAR(255)                            NOT NULL,
    display_order  INTEGER                                 NOT NULL,
    option_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_option_values PRIMARY KEY (id)
);

ALTER TABLE option_values
    ADD CONSTRAINT FK_OPTION_VALUES_ON_OPTION_TYPE FOREIGN KEY (option_type_id) REFERENCES option_types (id);

CREATE INDEX option_value_option_type_idx ON option_values (option_type_id);
CREATE UNIQUE INDEX uk_option_value_type_value ON option_values (option_type_id, value);