### Get Category Meta by Category ID
GET http://localhost:8080/api/categories/1/meta
Accept: application/json

###

### Get Meta - Fashion
GET http://localhost:8080/api/categories/2/meta
Accept: application/json

###

### Get Meta - Not Found (category or meta doesn't exist)
GET http://localhost:8080/api/categories/9999/meta
Accept: application/json
